[build]
  base = "."  # Set this to the directory containing your package.json if it's not in the root
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.18.0"  # Specify the Node.js version you're using